name: Build and publish sanjego Docker image

on:
  pull_request:
  push:
    branches:
      - master
      - development

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag merkrafter/sanjego:$(date +%F-%s)
    - name: Log in into Docker image registry
      run: docker login docker.pkg.github.com --username merkrafter
    - name: Publish Docker image
      run: docker push docker.pkg.github.com/merkrafter/sanjego/IMAGE_NAME:VERSION
