name: Python application

on:
  pull_request:
  push:
    branches: 
      - master
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # since main uses a sacred config function, it has several "unused" variables
        flake8 --per-file-ignores="main.py:F841" --max-line-length=120 --statistic
    - name: Test with pytest
      run: |
        pip install pytest
        python -m pytest --verbose test/*
